language: csharp
solution: ObjectMap.sln

before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore ObjectMap.sln
after_script:
  - nunit-console ObjectMap.Tests/bin/Release/ObjectMap.Tests.dll
